### ISSUE TITLE
LAPIS open preprocessing pipeline is crashing

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/LAPIS#159]
Error message:

```
lapis-proc  | 12:06:43.040 [main] INFO ch.ethz.lapis.source.ng.NextstrainFileToDatabaseService - finished updateAAMutations
lapis-proc  | 12:06:43.040 [main] INFO ch.ethz.lapis.source.ng.NextstrainFileToDatabaseService - starting updateMetadata
lapis-proc  | 12:13:06.503 [main] INFO ch.ethz.lapis.source.ng.NextstrainFileToDatabaseService - finished updateMetadata
lapis-proc  | 12:13:06.503 [main] INFO ch.ethz.lapis.source.ng.NextstrainFileToDatabaseService - started updateNextcladeData
lapis-proc  | Exception in thread "main" java.lang.reflect.InvocationTargetException
lapis-proc  |   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
lapis-proc  |   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
lapis-proc  |   at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
lapis-proc  |   at java.base/java.lang.reflect.Method.invoke(Method.java:568)
lapis-proc  |   at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
lapis-proc  |   at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
lapis-proc  |   at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
lapis-proc  |   at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
lapis-proc  | Caused by: java.lang.NumberFormatException: For input string: "C241T"
lapis-proc  |   at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
lapis-proc  |   at java.base/java.lang.Integer.parseInt(Integer.java:668)
lapis-proc  |   at java.base/java.lang.Integer.parseInt(Integer.java:786)
lapis-proc  |   at ch.ethz.lapis.source.ng.NextstrainGenbankNextcladeFileReader.lambda$next$1(NextstrainGenbankNextcladeFileReader.java:66)
lapis-proc  |   at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
lapis-proc  |   at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
lapis-proc  |   at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
lapis-proc  |   at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
lapis-proc  |   at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
lapis-proc  |   at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
lapis-proc  |   at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
lapis-proc  |   at ch.ethz.lapis.source.ng.NextstrainGenbankNextcladeFileReader.next(NextstrainGenbankNextcladeFileReader.java:76)
lapis-proc  |   at ch.ethz.lapis.source.ng.NextstrainGenbankNextcladeFileReader.next(NextstrainGenbankNextcladeFileReader.java:18)
lapis-proc  |   at ch.ethz.lapis.source.ng.NextstrainFileToDatabaseService.updateNextcladeData(NextstrainFileToDatabaseService.java:521)
lapis-proc  |   at ch.ethz.lapis.source.ng.NextstrainFileToDatabaseService.insertFilesIntoDatabase(NextstrainFileToDatabaseService.java:79)
lapis-proc  |   at ch.ethz.lapis.source.ng.NextstrainGenbankService.updateData(NextstrainGenbankService.java:37)
lapis-proc  |   at ch.ethz.lapis.LapisMain.run(LapisMain.java:85)
lapis-proc  |   at ch.ethz.lapis.LapisMain.main(LapisMain.java:39)
lapis-proc  |   ... 8 more
lapis-proc exited with code 1
```

I think that the `nextclade.tsv` file that we get from Nextstrain is malformed/wrong: https://github.com/nextstrain/ncov-ingest/issues/392

**Comment by chaoran-chen** [comment]
nextclade.tsv was fixed and the preprocessing works again.
